### ISSUE TITLE
Support for composer?

### ISSUE THREAD

**Issue by letharion** [solarphp/core#66]
Hi! I was looking for solar components on packagist, and couldn't find anything. Am I looking for the wrong thing, or does Solar not provided packagist/composer packages?

**Comment by pmjones** [comment]
Hey there -- sorry, Solar was developed _way_ before Composer, so no packages for it on packagist. Hell, you'd have to take Solar as a whole, since it's not well-decoupled. Sorry about that.

**Comment by pmjones** [comment]
Having said that, the installation instructions are here: http://solarphp.com/project/download

And for reference, the second version of Solar is called Aura, here: http://auraphp.com

Hope that helps at least a little.

**Comment by letharion** [comment]
Thank you. interestingly, I was contrasting Solar and Aura, not realizing at all that there was a connection between them. Sounds like I should take more of an interest in Aura, and less in Solar then.
